---
brew_taps:
  - caskroom/cask
  - caskroom/fonts
  - caskroom/versions

brew_pkgs:
  - ansible
  - mas
  - vim
  - wget
  - hugo
  - awscli
  - jq
  - elinks
  - certbot
  # shell utilities
  - fish
  - fzf
  - peco
  - direnv
  - ag
  - terminal-notifier
  - watch
  # git-related tools
  - ghq
  - hub
  - tig
  # for python
  - pyenv
  - flake8
  # for golang
  - go
  # for nodejs
  - nodebrew
  # for java
  - gradle
  - maven
  # for kotlin
  - kotlin
  - shyiko/ktlint/ktlint

brew_cask_pkgs:
  - java
  - java8
  - alfred
  - google-japanese-ime
  - google-trends
  - spotify
  - istat-menus5
  - flux
  - authy
  # Internet
  - google-chrome
  # Messaging
  - franz
  # Cloud drive
  - google-backup-and-sync
  - dropbox
  # for developing
  - iterm2
  - atom
  - dash
  - vagrant
  - virtualbox
  - docker
  - gitify
  # Photos
  - skitch
  - adobe-creative-cloud
  - google-nik-collection
  # QuickLook
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlstephen
  # Font
  - font-source-code-pro-for-powerline

pyenv_versions:
  - 3.6.3
  - anaconda3-4.4.0

nodebrew_versions:
  - v9.2.0

pip_global_pkgs:
  - rainbowstream
  - yapf
  - ipython
  - virtualenv

mas_pkgs:
  - {id: 408981434 , name: iMovie }
  - {id: 409183694 , name: Keynote }
  - {id: 409201541 , name: Pages }
  - {id: 409203825 , name: Numbers }
  - {id: 443987910 , name: 1Password }
  - {id: 497799835 , name: Xcode }
  - {id: 539883307 , name: LINE }
  - {id: 568494494 , name: Pocket }
  - {id: 585829637 , name: Todoist }
  - {id: 682658836 , name: GarageBand }
  - {id: 766939888 , name: 1Keyboard }
  - {id: 865500966 , name: Feedly }
  - {id: 918858936 , name: Airmail 3 }
  - {id: 946680495 , name: MARKETSPEED }
  - {id: 1039633667, name: Irvue}
  - {id: 1055511498, name: Day One}
  - {id: 1091189122, name: Bear }

apm_pkgs:
  - atom-beautify
  - file-icons
  - autocomplete-paths
  - smart-tab-name
  - show-ideographic-space
  - firacode
  - fonts
  - multi-cursor
  - git-plus
  - git-log
  - script
  - linter
  - linter-ui-default
  - intentions  # for linter-flake8
  - busy-signal  # for linter-flake8
  # Python
  - python-yapf
  - autocomplete-python
  - kite
  - magicpython
  - linter-flake8
  # -- Forntend
  - emmet
  # ES2015
  - linter-eslint
  - language-babel
  # CSS
  - pigments
  - linter-sass-lint

fisher_plugins:
  - anicode
  - ansible-completion
  - edc/bass
  - docker-completion
  - done
  - fzf
  - imgcat
  - pyenv
  - upto
  - vault
  - z
  - omf/peco
  - omf/theme-bobthefish
